language: android

dist: trusty

jdk:
  - oraclejdk8

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager)
  - sdkmanager tools

install: ./gradlew build --stacktrace

script:
  - ./gradlew check --stacktrace

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - GRADLE_OPTS="-Xmx768m -Xms256m -Xss1m" # To limit memory use on CI and avoid OOMs
    - secure: "OWlXD+oSQokTIEifXrFLuQVfBPlF9+iJoTm9ADac36Ouck4xMzSc33VLManQYJeW1xOkL/YyNJEi7N0/5xDyLXwOIMrpLdm/Tp6RXvK8xK5zqsWRLfruI3o9lHQRemb939PGesSQZ/PipzlE+cAmiTWf+P3STZ/L97nvu3ZKmTzd/bvnIG6ua+zrLfMwUJUsBC7hqTreHWYdkGEKFdD98BUqAGkR5LKUtIm590vZAvMuAtxOSjEBnF72Gzpj2C44N1GGiC2y2Pp7ubcmzAXhXM5fWJnF8XHne67ymnol8HZgvZ2njYGd23LIh/eJMWL2gH7AX5uvE2VM3BVBpqESH3Gg3VM4hrZ1feodmHk/t+XqFA4jWAQNG3U2apKZkZmWgcRtIKrHGwdPkJaIU6pAcNzqIw6k8se6uo2cOLw+ukr/ICrCrj+J1xet2yUZAexm3xgGDbpL3vUb+lErg50x7fuWQbIkINHPhe7FewAnl5Zt8GVXEb4Sq/Uiyzd9hbc23812wJ2w4tGC2w2DYw00LpLWGfu67aGuubeJGkjh/BVGB4udiyDYk/yrqA7/7UKbuu9u7MT3d4nrwv/fUqRd8tyQlqrGzp+He3Rz+U+c0Mm4PzyzBXF2Ac2SsTsjOpGco67/Xi60iTL39wxEnl0M9HwqvxLM6nel0gL4ELN8nKw="
    - secure: "DAVyUCMs1n3+2jGAXQ0uw3xbKc2tZD1YaZ0+zxD6FrNiedvfrpx0b0JKdb39KW1DgRLxl2sy2HHmomRnZqIXzANH5GsVFyH3stM19///Ang+4iqc4DEkEzv6UIhVgsCFs9Ix/xr6jxsfEO2CigHzbdI1s/YDGZS1X/H6skxCfVjSHhwgc8+mwcyDzf2ZALdIUUMNG+mxKBEjey1OZN8MLYNkUHOPJng4PKx3kQkzAM2cyulTB1oGuqvQFE7TqFzC5JrBRhY23hjlWDivrh1lwdSM6owERUHq4CTuQomxrqYX23pzxsDYzJnL7SN4Z10e26VcSqJsAvMj+hOaYzmb+B1zXfeQr7aLTiKkKQyjxK5/Us3ajVBa1q2usn4HGAuvLXg0INRmBYvQXd5Y4Ls0ikRQ4i1+dcvPCRrZeHYk8hIe/mWVXXuBYQDWPxX9pLELvPNmTw6AVJku1rGImkw2s67bEoEGN+XdAVrdUfZkZJDc8yVIsO9tIRJ9cvJDBM0V+wSjqZ5chUlfLH7vKGaByHPW3wwJl4iE7+Alc00Pwrg05Z+XJnzxS38FgYlsq8bQuYJa+RfNP5EAp3Wm/bAOB6nuDjAnZ2B/+9n9QL+Qo16Uyq/ss7X9RZaErEWx9SC0TQJjfj9w6YZvbha8lenERczKbK2b6glV3TDDWlbvVpU="

branches:
  only:
    - master

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
